### ISSUE TITLE
Some urgent questions about facets result

### ISSUE THREAD

**Issue by ShixiangWang** [mskcc/facets#147]
Dear developer,

I have some urgent questions when I check the result from facets. 

I found some cancer patients have many regions with copy number 0, so I checked it by comparing the original tumor and normal bam with IGV. I have two questions related to the following figures.

1. The copy number values for some regions are not reported, but there are many mapped reads.

![image](https://user-images.githubusercontent.com/25057508/69043930-f4cbed00-0a2e-11ea-8aa0-e17e1d0fc455.png)

2. (my key question), why regions with copy number value 0 have comparable read counts in tumor bam and normal bam? How the facets infer copy number 0 from a situation like this?

![image](https://user-images.githubusercontent.com/25057508/69044269-97846b80-0a2f-11ea-88f7-1cf804fdd80b.png)

All the results are obtained by default options. Is this related to the critical value `cval`? I also checked the data from `cval=300`, but similar result returned.

I don't think 0 should be the right copy number for the regions, but I can't figure out why. If it is right, I can't explain why a tumor can have so many deep deletions.

![image](https://user-images.githubusercontent.com/25057508/69045492-e8955f00-0a31-11ea-9aca-c0dbc5f34a38.png)

```
> packageVersion('facets')
[1] ‘0.6.0’
```

This is very important to my project, I'm looking forward to a quick reply.

Best,
Shixiang

**Comment by shenmskcc** [comment]
It seems to me your data can only be used to infer gene/exon-level copy
number, not applicable for FACETS analysis.

**Comment by ShixiangWang** [comment]
Why? This is WES more than 100X, the major target for facets. I have many samples, how do know if they can be used for facets?

**Comment by veseshan** [comment]
The integer copy number plot in the bottom implies there is a problem with the sample. At the ver least it is hyper-segmented. But without the logR and logOR plots that are produced by facets it is impossible to diagnose the problem.

**Comment by ShixiangWang** [comment]
@veseshan Thanks for your reply. I have attached the corresponding file generated by facets, please take a look.

What do you mean 'hyper-segmented'? Could you explain it? How can I avoid this by setting a universe threshold (like `cval`). I have used facets to process about 1000 samples with default parameters.

[facet_result](https://github.com/mskcc/facets/files/3864295/file_show.pdf)

Best,
Shixiang

**Comment by veseshan** [comment]
I have included a part (chr1-3) of the figure you uploaded

![facets-issue147](https://user-images.githubusercontent.com/12280668/69157735-63eb2500-0ab3-11ea-97d6-49fe2a114a29.png)

The top part is the logR and bottom logOR. By hyper-segmentation I mean many small segments. Usually that happens when sample is noisy. But your sample is showing weird patterns. The overall range of logR is between -1.5 and 1.5 but there are quite a few intervals where it drops quite a bit lower. However these don't appear to be contiguous regions and spread over the whole genome. Also the drop in logR is not accompanied by much of a change in allelic imbalance (logOR) that single copy loss should have induced. Note that the change in logR is very pronounced and thus tumor fraction if real should be high. So only logical explanation is homozygous deletion. However they are too many of them and so I believe this is assay artifact rather than real.

**Comment by ShixiangWang** [comment]
@veseshan  Thanks for your professional explanation and conclusion. I will take the time to understand the detail.

Best,
Shixiang

**Comment by ipstone** [comment]
Just a question/comment here: are these samples FFPE archived tumor samples ? - which might explain the observed hyper-segmentations.
