### ISSUE TITLE
dependency pctGCdata has unclear requirements

### ISSUE THREAD

**Issue by jbedo** [mskcc/facets#160]
Facets requires pctGCdata >= 3.0.0 as declared in DESCRIPTION, however no such release is available, indeed no releases are available in the referenced veseshan/pctGCdata repository. Can you clarify which revision of pctGCdata should be used with facets v0.6.1?

**Comment by stevekm** [comment]
@jbedo maybe helpful, this is the Dockerfile used with `facets-suite` which includes a facets installation;

https://github.com/mskcc/facets-suite/blob/master/Dockerfile

in the container listed here; https://hub.docker.com/layers/stevekm/facets-suite/2.0.6/images/sha256-1809a092ab07bace2c3d3bd32017487f976ed8b6dbdd17f26126f2d5d5079978?context=explore

It appears that `pctGCdata     0.3.0` is installed.

**Comment by jbedo** [comment]
Unfortunately that doesn't clarify things. The pctGCdata repo does not have any releases tagged for 0.3.0. Looking at the commits, the DESCRIPTION file was updated to 0.3.0 in https://github.com/mskcc/pctGCdata/commit/961dc95f75722d0cf60baabf5f667fd60d0ae188, but there has been 10 commits since then with the same 0.3.0 version. For reproducibility, I'd like to know which revision the latest release of facets should be used with.

**Comment by veseshan** [comment]
pctGDdata is a data package. Nothing had changed in the data or the single accessor function in the package. So I believe you should have reproducible results no matter what.

**Comment by doliv071** [comment]
I would like to second @jbedo 's concerns. The issue I think is that the installation process involved using `devtools::install_github()` which has the disadvantage of changing with each commit. If there is a change to this repo then all installation procedures which deploy pctGCdata using the recommended `devtools::install_github()` will have unexpected results. 

If I could make a suggestion, the simplest solution would be to simply tag the repo as it exists now as v0.3.0 so that the error provided by `facets` matches a release of the pctGCdata package.

**Comment by veseshan** [comment]
I have created a v0.3.0 release of pctGCdata. If ```devtools::install_github()``` doesn't work the package can be downloaded and installed using ``` R CMD INSTALL pkgsrc```
