### ISSUE TITLE
critical value

### ISSUE THREAD

**Issue by tamaraprieto** [mskcc/facets#17]
Hello, 

I have observed that depending on the critical value applied, I get more or less NA values in columns mafR.clust, cf.em and lcn.em  of the cncf table which outputs the function procSample and I need the lcn.em value in order to construct the trees with the software medicc (https://bitbucket.org/rfs/medicc). 

mafR.clust     |  start              |    end                 | cf.em             | tcn.em   |  lcn.em
0.01875509   | 193096          |  88742250       | 1.0000000    |  2           |   1
4.10692463   |88780369      |  94474121        | 0.8668902   |   1           |   0
0.02143682   | 94501610      |  107427767      | 1.0000000    |  2           |   1
NA                   | 107436455   |  108412448     |  0.8046747   |   1           |  0
NA                   | 108464362   |  111899267      |  NA                |   2           |  NA

I am confused about the default values of this cval in the functions preProcSample (cval=25) and procSample (cval=150). In addition to this, the argument dipLogR inside the procSample function says that "diploid level obtained from a fit, typically using a higher cval, can be used with lower cval to recover focal changes". Do this mean that I should run first preProcSample and then twice procSample,  first time using a cval higher than 150 and dipLogR=NULL and second time cval=150 and dipLogR equal to the output of the first round?

In Olshen&Vankatraman.2004.Biostatistic  I found that "This critical value when the Xi are normal can again be computed using Monte Carlo simulations or the approximation given by Siegmund (1986) for the tail probability." Should I use a Monte Carlo simulation to get my cvalues?

Sorry for the incoveniences, I am a biologist and my statistics skills are not very good. And thank you for the software, it is just what I needed.I would be very grateful if you could solve my doubts, thank you in advance

**Comment by veseshan** [comment]
The FACETS algorithm works somewhat differently from the CBS algorithm. Instead of segmenting it at a fixed p-value threshold we use a critical value (cval) threshold to segment. Ideally this should change with sample size but we found that it was having minimal effect on the segmentation.

preProcSample is used to generate a fine segmentation of the sample which is then coarsened in procSample so that we can avoid hyper-segmentation due to waves that are still in the data (despite GC correction). We also add back large focal changes we found in preProcSample. The default values we use are what worked best for whole exome sequencing of sufficient depth (50x or higher). You should always run preProcSample before running procSample for the first time since procSample expects the data to be in the form of the output of preProcSample. You can run procSample with any cval but specify the dipLogR from a prior fit (or specify it to be what you think it should be). You can specify cval that is large enough to avoid hyper-segmentation. 

As for the NAs you see, the NAs arise from the fact that the segment does not have sufficient numbers of heterozygous SNPs to help estimate the allele specific copy number. This typically happens in focal changes (mostly amplification since deletions are mostly estimated to be zero for lcn).

**Comment by tamaraprieto** [comment]
Thank you very much. I have new questions regarding your answer: 

**1.** So with "specify the dipLogR from a prior fit" you mean specify the dipLogR which outputs procSample with default cval=150 and dipLogR=NULL as follows?

`fit1=procSample(OutputPreProcSample, cval=150, min.nhet=15, dipLogR=NULL)
  fit2=procSample(OutputPreProcSample, cval=500, min.nhet=15, dipLogR=fit1$dipLogR)
` 

**2.** As I have understood I should keep cval=25 when running preProcSample and increase the cval in ProcSample if necessary to avoid hyper-segmentation. Is it ok?

**3.** Is there a safe way to get a value other than NAs for the allele specific copy number or does it depend on my data?I tried reducing the parameter min.nhet to 4 (my lowest number of heterozygous SNPs by sample) but it does not work.   

I am creating the input file in this way:
`snp-pileup \
           --gzip \
           --progress \
           --pseudo-snps=250 \
           --min-map-quality=10 \
           --min-base-quality=10 \
           dbsnp_138.b37.InSureSelectXTAllExonsV5.SNVs.vcf \
           InputFacets_250_CLL01-04_CLL01-01.csv \
           Control.recal.bam \
           Tumor.recal.bam
`
**4.** But in this code above, what should be the pseudo-snps value?As snp.nbhd=250 I assumed that choosing a smaller value didn't make much sense...

**5.** I found another script that also creates the input using snplocs instead of a vcf file. Should I use that one instead of this script above?

**Comment by veseshan** [comment]
1. Yes that is the way to use it.
2. Sometimes it may be necessary to use a larger cval in preProcSample. For instance WGS. But otherwise cval of 25 is a good choice for preProcSample.
3. You can use a lower min.nhet and the it will produce a number. But the uncertainty in it will be high.
4. I usually generate a pileup file with pseudo-snps=50 as it lets me use different snp.nbhd (lower ones if the insert sizes are small) without having regenerate the count data.
5. The old perl code (available from google site) was used for all the analysis in the NAR manuscript. It is there for posterity (so that all the analysis can be repeated in necessary). The C++ code here is faster and better (can be used with any genome build) etc. So you should use this code.

Venkat

**Comment by veseshan** [comment]
By the way min.nhet is the minimum number of hets per segment.

**Comment by tamaraprieto** [comment]
That was very helpful. Thank you very much
