### ISSUE TITLE
snp-pileup: No 0,0,0,0 counts, but lots with a single-count SNPs

### ISSUE THREAD

**Issue by HenrikBengtsson** [mskcc/facets#21]
I ran:
```sh
$ snp-pileup $vcf foo.csv $bam
```
using the [suggested VCF](ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-common_all.vcf.gz) and a human BAM file that is from Exome-Seq.

Because it's exome capture data, I would expected lots of `0,0,0,0` output, but there are none.  However, there're lots of single-count SNPs.  What could be the reason?  Are you adding `+1` or something on purpose?

```sh
$ wc -l foo.csv 
4868438 foo.csv

## No zero calls
$ grep -F ",0,0,0,0" foo.csv | wc -l
0

## Lots of single-count SNPs (last one is a bit odd)
$ grep -F ",1,0,0,0" foo.csv | wc -l
608585   ## 12.5%
$ grep -F ",0,1,0,0" foo.csv | wc -l
603281   ## 12.1%
$ grep -F ",0,0,1,0" foo.csv | wc -l
1191404  ## 24.4%
$ grep -F ",0,0,0,1" foo.csv | wc -l
0        ## 0.0%

$ head -3 foo.csv
Chromosome,Position,Ref,Alt,File1R,File1A,File1E,File1D
chr1,13110,G,A,10,1,0,0
chr1,13116,T,G,7,0,0,0

$ tail -3 foo.csv
chrY,26391904,G,A,0,0,1,0
chrY,26391930,G,A,0,1,0,0
chrY,26397128,A,G,0,0,1,0
```

**Comment by veseshan** [comment]
Since we are only interested in loci where there is at least one read, the program writes only those loci that have at least one read. In fact it is a good idea to set the minimum read count in the normal sample to a larger number (for example --min-read-counts=25,0).

Also note that reasSnpMatrix assumes File1 is normal and File2 is Tumor. So use this program with bam files in the normal-tumor order. 

Venkat

**Comment by HenrikBengtsson** [comment]
Ah... ok, so zero counts are not outputted.  A side effect is that one won't be able to know what all the SNP locations of the VCF are from the outputted CSV file.  That's ok with me.

Thxs

PS. I like how fast `snp-pileup` is :)
