### ISSUE TITLE
Choosing different cvals for preProcSample and procSample

### ISSUE THREAD

**Issue by ckandoth** [mskcc/facets#76]
Hi @veseshan. For IMPACT samples, [our wrapper](https://github.com/mskcc/facets-suite/blob/1.5.5/doFacets.R#L221-L225) around facets has always used the same `cval` for `preProcSample` and `procSample` before running `emcncf`. However, in your [facets-wrapper](https://github.com/mskcc/facets/blob/v0.5.14/R/facets-wrapper.R) the defaults are `25` and `150` respectively. And later in that wrapper, you ensure that the `preProcSample cval is smaller than procSample cval`. What is the rationale behind different cvals for `preProcSample` and `procSample`, and have we been doing it wrong? Thanks much!

**Comment by veseshan** [comment]
In the current form of the package (as of v0.5.0) preProcsample grows a large segmentation tree which is also used to identify focal changes (3 mads away from adjacent segments). procSample first identifies focal changes, then prunes the tree to remove all changes attributable to waves that still remain after GC correction etc. Hence the default has been 25 for preProc and 150 for proc. The 150 is based on WES experience. For IMPACT I use 75 or 100 since the number of loci (snps) are far fewer. Using the same cval for both will make it hard to detect focal changes. Before v0.5.0 focal change was done by a two pass approach since noise sample needed larger cval.

The statistical rationale is that the mean of the standardized (x1bar - x2bar) is mu*sqrt(n1*n2/(n1+n2))
If n1+n2 is fixed then it can get large if either mu gets large of if n1*n2 gets large. For focal changes n1*n2 is likely small and so larger cval will kill off the ability to detect them.

**Comment by veseshan** [comment]
Your choices are reasonable.
